"use client";

import React, { useState, useEffect } from "react";
import Head from "next/head";
import Stack from "@mui/material/Stack";
import Header from "./components/Header";
import Tabs from "@mui/material/Tabs";
import Tab from "@mui/material/Tab";
import TabPanel from "./components/TabPanel";
import KehadiranTab from "./components/KehadiranTab";
import BahanAjar from "./components/BahanAjar";
import Tugas from "./components/Tugas";
import { useRouter } from "next/navigation";
import { kelasData } from "./data/kelas";
import BerandaTab from "./components/BerandaTab";
import Nilai from "./components/Nilai";
import { Box } from "@mui/material";

const Classroom = () => {
  const [value, setValue] = useState(0);
  const router = useRouter();
  const { id } = 1;

  const data = kelasData.find((item) => item.id === parseInt(id));

  const handleChange = (event, newValue) => {
    setValue(newValue);
  };

  return (
    <Box
      sx={{ display: "flex", flexDirection: "column", maxWidth: 800, width:"100%", my: 2 }}
    >
      <Head>
        <title>Beranda | SISVA Classroom</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header title={`Matematika - X IPA 1`} subtitle="Alwi Sukra S.Pd, M.T" />
      <Stack
        width="100%"
        height="100%"
        pt={{ xs: 8, sm: 0 }}
        px={{ xs: 2, sm: 0 }}
      >
        <Tabs
          value={value}
          onChange={handleChange}
          centered
          sx={{
            width: "100%",
            borderBottom: "1px solid #E5E5E5",
            "& .MuiTab-root": {
              p: "16px 12px",
              fontSize: "12px",
              minWidth: 64,
            },
          }}
        >
          <Tab label="Beranda" />
          <Tab label="Bahan Ajar" />
          <Tab label="Tugas" />
          <Tab label="Nilai" />
          <Tab label="Kehadiran" />
        </Tabs>
        <Stack mt={2}>
          <TabPanel value={value} index={0}>
            <BerandaTab />
          </TabPanel>
          <TabPanel value={value} index={1}>
            <BahanAjar />
          </TabPanel>
          <TabPanel value={value} index={2}>
            <Tugas />
          </TabPanel>
          <TabPanel value={value} index={3}>
            <Nilai />
          </TabPanel>
          <TabPanel value={value} index={4}>
            <KehadiranTab />
          </TabPanel>
        </Stack>
      </Stack>
    </Box>
  );
};

export default Classroom;
