import {
  educationLevels,
  genders,
  guardians,
  incomeLevels,
  lifeStatus,
  nationalities,
  permissions,
  relationships,
  religions,
  subject_types,
  types,
} from '@/globalcomponents/Variable';

export const formAddCurriculumFields = [
  {
    name: 'period_name',
    label: 'Periode',
    placeholder: 'Periode',
    md: 6,
    type: 'select',
    data: [],
  },
  {
    name: 'curriculum_name',
    label: 'Kurikulum',
    placeholder: 'Kurikulum',
    md: 6,
    type: 'select',
    data: [],
  },
  {
    name: 'study_program',
    label: 'Program Studi',
    placeholder: 'Program Studi',
    md: 6,
    type: 'select',
    data: [],
  },
  {
    name: 'grade',
    label: 'Tingkatan',
    placeholder: 'Tingkatan',
    md: 6,
    type: 'select',
    data: [],
  },
];
export const formEditPeriodFields = [
  {
    name: 'period_name',
    label: 'Periode',
    placeholder: 'Periode',
    md: 6,
    type: 'text',
  },
  {
    name: 'period',
    label: 'Rentang Waktu',
    placeholder: 'Rentang Waktu',
    md: 6,
    type: 'month-range',
  },
  {
    name: 'status',
    label: 'Status',
    placeholder: 'Status',
    md: 6,
    type: 'select',
    data: [
      { slug: 'inactive', title: 'Belum Aktif' },
      { slug: 'active', title: 'Aktif' },
    ],
  },
];
export const formAddPeriodFields = [
  {
    name: 'period_name',
    label: 'Periode',
    placeholder: 'Periode',
    md: 6,
    type: 'text',
  },

  {
    name: 'period',
    label: 'Rentang Waktu',
    placeholder: 'Rentang Waktu',
    md: 6,
    type: 'month-range',
  },
];
export const formAddSyllabusFields = [
  {
    name: 'curriculum_name',
    label: 'Nama',
    placeholder: 'Nama',
    md: 6,
    type: 'select',
    data: [],
  },
  {
    name: 'study_program',
    label: 'Program Studi',
    placeholder: 'Program Studi',
    md: 6,
    type: 'select',
    data: [],
  },
  {
    name: 'subject',
    label: 'Mata Pelajaran',
    placeholder: 'Mata Pelajaran',
    md: 6,
    type: 'select',
    data: [],
  },
  {
    name: 'grade',
    label: 'Tingkatan',
    placeholder: 'Tingkatan',
    md: 6,
    type: 'select',
    data: [
      { slug: 'X', title: 'X' },
      { slug: 'XI', title: 'XI' },
      { slug: 'XII', title: 'XII' },
    ],
  },
  {
    name: 'syllabus_uri',
    label: 'Silabus',
    placeholder: 'Silabus',
    md: 6,
    type: 'file',
  },
];
export const formAddSubjectFields = [
  {
    name: 'curriculum_name',
    label: 'Nama Kurikulum',
    placeholder: 'Nama',
    md: 6,
    type: 'select',
    data: [],
  },
  {
    name: 'study_program',
    label: 'Program Studi',
    placeholder: 'Program Studi',
    md: 6,
    type: 'select',
    data: [],
  },
  {
    name: 'subject',
    label: 'Mata Pelajaran',
    placeholder: 'Mata Pelajaran',
    md: 6,
    type: 'text',
  },
  {
    name: 'subject_type',
    label: 'Tipe',
    placeholder: 'Tipe',
    md: 6,
    type: 'select',
    data: subject_types,
  },
];
export const formAddStudyProgramFields = [
  {
    name: 'name',
    label: 'Program Studi',
    placeholder: 'Nama',
    md: 6,
    type: 'text',
  },
  {
    name: 'code',
    label: 'Kode',
    placeholder: 'Kode',
    md: 6,
    type: 'text',
  },
];

export const formAddStaffFields = [
  {
    name: 'name',
    label: 'Nama',
    placeholder: 'Nama',
    md: 6,
    type: 'text',
  },
  {
    name: 'username',
    label: 'Username',
    placeholder: 'Username',
    md: 6,
    type: 'text',
  },
  {
    name: 'type',
    label: 'Tipe',
    placeholder: 'Tipe',
    md: 6,
    type: 'select',
    data: types,
  },
  {
    name: 'permissions',
    label: 'Akses',
    placeholder: 'Akses',
    md: 6,
    type: 'multiple-select',
    data: permissions,
  },
  {
    name: 'password',
    label: 'Password',
    placeholder: 'Password',
    md: 6,
    type: 'password',
  },
  {
    name: 'password_confirm',
    label: 'Konfirmasi Password',
    placeholder: 'Konfirmasi Password',
    md: 6,
    type: 'password',
  },
];
export const formAddStudentFields = [
  {
    name: 'name',
    label: 'Nama',
    placeholder: 'Nama',
    md: 6,
    type: 'text',
  },
  {
    name: 'username',
    label: 'Username',
    placeholder: 'Username',
    md: 6,
    type: 'text',
  },
  {
    name: 'password',
    label: 'Password',
    placeholder: 'Password',
    md: 6,
    type: 'password',
  },
  {
    name: 'password_confirm',
    label: 'Konfirmasi Password',
    placeholder: 'Konfirmasi Password',
    md: 6,
    type: 'password',
  },
];

export const formStudentBasicFields = [
  {
    name: 'name',
    label: 'Nama',
    placeholder: 'Nama',
    md: 6,
    type: 'text',
  },
  {
    name: 'username',
    label: 'Username',
    placeholder: 'Username',
    md: 6,
    type: 'text',
  },
];

export const formStudentBiodataFields = [
  {
    name: 'email',
    label: 'Email',
    placeholder: 'Email',
    md: 6,
    type: 'text',
  },
  {
    name: 'phone',
    label: 'Nomor Telepon',
    placeholder: 'Nomor Telepon',
    md: 6,
    type: 'text',
  },
  {
    name: 'gender',
    label: 'Jenis Kelamin',
    placeholder: 'Jenis Kelamin',
    md: 6,
    type: 'select',
    data: genders,
  },
  {
    name: 'nationality',
    label: 'Kewarganegaraan',
    placeholder: 'Kewarganegaraan',
    md: 6,
    type: 'select',
    data: nationalities,
  },
  {
    name: 'personal_id',
    label: 'NIK',
    placeholder: 'NIK',
    md: 6,
    type: 'text',
  },
  {
    name: 'education_id',
    label: 'NISN',
    placeholder: 'NISN',
    md: 6,
    type: 'text',
  },
  {
    name: 'religion',
    label: 'Agama',
    placeholder: 'Agama',
    md: 12,
    type: 'select',
    data: religions,
  },
  {
    name: 'address',
    label: 'Alamat',
    placeholder: 'Alamat',
    md: 12,
    type: 'text',
  },
  {
    name: 'profile_image_uri',
    label: 'Foto Profil',
    placeholder: 'Foto Profil',
    md: 12,
    type: 'photo',
  },
];

export const formStudentParentsFields = [
  { type: 'title', label: 'Wali Murid' },
  {
    name: 'guardian_type',
    // label: "Wali Murid",
    // placeholder: "Wali Murid",
    md: 12,
    type: 'select',
    data: guardians,
  },
  { type: 'divider' },
  { type: 'title', label: 'Informasi Ayah' },
  {
    name: 'father_name',
    label: 'Nama',
    placeholder: 'Nama',
    md: 12,
    type: 'text',
  },
  {
    name: 'father_email',
    label: 'Email',
    placeholder: 'Email',
    md: 6,
    type: 'text',
  },
  {
    name: 'father_phone',
    label: 'Nomor Telepon',
    placeholder: 'Nomor Telepon',
    md: 6,
    type: 'text',
  },
  {
    name: 'father_occupation',
    label: 'Profesi',
    placeholder: 'Profesi',
    md: 6,
    type: 'text',
  },
  {
    name: 'father_education',
    label: 'Pendidikan Terakhir',
    placeholder: 'Pendidikan Terakhir',
    md: 6,
    type: 'select',
    data: educationLevels,
  },
  {
    name: 'father_income',
    label: 'Pemasukan Bulanan',
    placeholder: 'Pemasukan Bulanan',
    md: 12,
    type: 'select',
    data: incomeLevels,
  },
  {
    name: 'father_birth_year',
    label: 'Tahun Lahir',
    placeholder: 'Tahun Lahir',
    md: 6,
    type: 'text',
  },
  {
    name: 'father_life_status',
    label: 'Status',
    placeholder: 'Status',
    md: 6,
    type: 'select',
    data: lifeStatus,
  },
  {
    name: 'father_religion',
    label: 'Agama',
    placeholder: 'Agama',
    md: 12,
    type: 'select',
    data: religions,
  },
  {
    name: 'father_address',
    label: 'Alamat',
    placeholder: 'Alamat',
    md: 12,
    type: 'text',
  },
  { type: 'divider' },
  { type: 'title', label: 'Informasi Ibu' },
  {
    name: 'mother_name',
    label: 'Nama',
    placeholder: 'Nama',
    md: 12,
    type: 'text',
  },
  {
    name: 'mother_occupation',
    label: 'Profesi',
    placeholder: 'Profesi',
    md: 6,
    type: 'text',
  },
  {
    name: 'mother_education',
    label: 'Pendidikan Terakhir',
    placeholder: 'Pendidikan Terakhir',
    md: 6,
    type: 'select',
    data: educationLevels,
  },
  {
    name: 'mother_income',
    label: 'Pemasukan Bulanan',
    placeholder: 'Pemasukan Bulanan',
    md: 12,
    type: 'select',
    data: incomeLevels,
  },
  {
    name: 'mother_email',
    label: 'Email',
    placeholder: 'Email',
    md: 6,
    type: 'text',
  },
  {
    name: 'mother_phone',
    label: 'Nomor Telepon',
    placeholder: 'Nomor Telepon',
    md: 6,
    type: 'text',
  },
  {
    name: 'mother_birth_year',
    label: 'Tahun Lahir',
    placeholder: 'Tahun Lahir',
    md: 6,
    type: 'text',
  },
  {
    name: 'mother_life_status',
    label: 'Status',
    placeholder: 'Status',
    md: 6,
    type: 'select',
    data: lifeStatus,
  },
  {
    name: 'mother_religion',
    label: 'Agama',
    placeholder: 'Agama',
    md: 12,
    type: 'select',
    data: religions,
  },
  {
    name: 'mother_address',
    label: 'Alamat',
    placeholder: 'Alamat',
    md: 12,
    type: 'text',
  },

  { type: 'divider' },
  { type: 'title', label: 'Informasi Wali' },
  {
    name: 'guardian_name',
    label: 'Nama',
    placeholder: 'Nama',
    md: 12,
    type: 'text',
  },
  {
    name: 'guardian_gender',
    label: 'Jenis Kelamin',
    placeholder: 'Jenis Kelamin',
    md: 6,
    type: 'select',
    data: genders,
  },
  {
    name: 'guardian_relationship',
    label: 'Hubungan',
    placeholder: 'Hubungan',
    md: 6,
    type: 'select',
    data: relationships,
  },
  {
    name: 'guardian_occupation',
    label: 'Profesi',
    placeholder: 'Profesi',
    md: 6,
    type: 'text',
  },
  {
    name: 'guardian_education',
    label: 'Pendidikan Terakhir',
    placeholder: 'Pendidikan Terakhir',
    md: 6,
    type: 'select',
    data: educationLevels,
  },
  {
    name: 'guardian_income',
    label: 'Pemasukan Bulanan',
    placeholder: 'Pemasukan Bulanan',
    md: 12,
    type: 'select',
    data: incomeLevels,
  },
  {
    name: 'guardian_email',
    label: 'Email',
    placeholder: 'Email',
    md: 6,
    type: 'text',
  },
  {
    name: 'guardian_phone',
    label: 'Nomor Telepon',
    placeholder: 'Nomor Telepon',
    md: 6,
    type: 'text',
  },
  {
    name: 'guardian_birth_year',
    label: 'Tahun Lahir',
    placeholder: 'Tahun Lahir',
    md: 6,
    type: 'text',
  },
  {
    name: 'guardian_life_status',
    label: 'Status',
    placeholder: 'Status',
    md: 6,
    type: 'select',
    data: lifeStatus,
  },
  {
    name: 'guardian_religion',
    label: 'Agama',
    placeholder: 'Agama',
    md: 12,
    type: 'select',
    data: religions,
  },
  {
    name: 'guardian_address',
    label: 'Alamat',
    placeholder: 'Alamat',
    md: 12,
    type: 'text',
  },
];

export const formStaffBasicFields = [
  {
    name: 'name',
    label: 'Nama',
    placeholder: 'Nama',
    md: 6,
    type: 'text',
  },
  {
    name: 'username',
    label: 'Username',
    placeholder: 'Username',
    md: 6,
    type: 'text',
  },
  {
    name: 'type',
    label: 'Tipe',
    placeholder: 'Tipe',
    md: 6,
    type: 'select',
    data: types,
  },
  {
    name: 'permissions',
    label: 'Akses',
    placeholder: 'Akses',
    md: 6,
    type: 'multiple-select',
    data: permissions,
  },
];

export const formStaffBiodataFields = [
  {
    name: 'email',
    label: 'Email',
    placeholder: 'Email',
    md: 6,
    type: 'text',
  },
  {
    name: 'phone',
    label: 'Nomor Telepon',
    placeholder: 'Nomor Telepon',
    md: 6,
    type: 'text',
  },
  {
    name: 'gender',
    label: 'Jenis Kelamin',
    placeholder: 'Jenis Kelamin',
    md: 6,
    type: 'select',
    data: genders,
  },
  {
    name: 'nationality',
    label: 'Kewarganegaraan',
    placeholder: 'Kewarganegaraan',
    md: 6,
    type: 'select',
    data: nationalities,
  },
  {
    name: 'personal_id',
    label: 'NIK',
    placeholder: 'NIK',
    md: 6,
    type: 'text',
  },
  {
    name: 'education_id',
    label: 'NUPTK',
    placeholder: 'NUPTK',
    md: 6,
    type: 'text',
  },
  {
    name: 'religion',
    label: 'Agama',
    placeholder: 'Agama',
    md: 12,
    type: 'select',
    data: religions,
  },
  {
    name: 'address',
    label: 'Alamat',
    placeholder: 'Alamat',
    md: 12,
    type: 'text',
  },
  {
    name: 'profile_image_uri',
    label: 'Foto Profil',
    placeholder: 'Foto Profil',
    md: 12,
    type: 'photo',
  },
];

export const formChangePasswordFields = [
  {
    name: 'current_password',
    label: 'Password Lama',
    placeholder: 'Password Lama',
    md: 12,
    type: 'password',
  },
  {
    name: 'new_password',
    label: 'Password Baru',
    placeholder: 'Password Baru',
    md: 6,
    type: 'password',
  },
  {
    name: 'new_password_confirm',
    label: 'Konfirmasi Password Baru',
    placeholder: 'Konfirmasi Password Baru',
    md: 6,
    type: 'password',
  },
];
export const formResetPasswordFields = [
  {
    name: 'new_password',
    label: 'Password Baru',
    placeholder: 'Password Baru',
    md: 6,
    type: 'password',
  },
  {
    name: 'new_password_confirm',
    label: 'Konfirmasi Password Baru',
    placeholder: 'Konfirmasi Password Baru',
    md: 6,
    type: 'password',
  },
];

export const formSchoolDetailsFields = [
  {
    name: 'name',
    label: 'Nama Sekolah',
    placeholder: 'Nama Sekolah',
    md: 6,
    image: false,
  },
  {
    name: 'abbreviation',
    label: 'Nama Singkatan',
    placeholder: 'Nama Singkatan',
    md: 6,
    image: false,
  },
  {
    name: 'identifier_value',
    label: 'NPSN',
    placeholder: 'NPSN',
    md: 6,
    image: false,
  },
  {
    name: 'code',
    label: 'Kode Sekolah',
    placeholder: 'Kode Sekolah',
    md: 6,
    image: false,
  },
  {
    name: 'email',
    label: 'Email',
    placeholder: 'Email',
    md: 6,
    image: false,
  },
  {
    name: 'nomorTelepon',
    label: 'Nomor Telepon',
    placeholder: 'Nomor Telepon',
    md: 6,
    image: false,
  },
  {
    name: 'alamat',
    label: 'Alamat',
    placeholder: 'Alamat Sekolah',
    md: 12,
    image: false,
  },
  {
    name: 'logo_uri',
    label: 'Logo Sekolah',
    placeholder: 'Upload logo untuk identitas sekolah',
    md: 12,
    image: true,
  },
];

export const formSchoolTypeFields = [
  {
    name: 'education_type',
    label: 'Jenis Sekolah',
    placeholder: 'Jenis Sekolah',
    md: 6,
    image: false,
    data: [
      {
        value: 'general',
        label: 'Umum',
      },
      {
        value: 'madrasa',
        label: 'Madrasah',
      },
      {
        value: 'other',
        label: 'Lainnya',
      },
    ],
  },
  {
    name: 'education_level',
    label: 'Tingkatan Sekolah',
    placeholder: 'Tingkatan Sekolah',
    md: 6,
    image: false,
    data: [
      {
        value: 'elementary',
        label: 'SD/MI',
      },
      {
        value: 'junior_high',
        label: 'SMP/MTS',
      },
      {
        value: 'senior_high',
        label: 'SMA/SMK/MA',
      },
      {
        value: 'other',
        label: 'Lainnya',
      },
    ],
  },
  {
    name: 'education_ownership_type',
    label: 'Kepemilikan Sekolah',
    placeholder: 'Kepemilikan Sekolah',
    md: 6,
    image: false,
    data: [
      {
        value: 'public',
        label: 'Negeri',
      },
      {
        value: 'private',
        label: 'Swasta',
      },
    ],
  },
];

export const formAddSubjectTeacher = [
  {
    name: 'subject',
    label: 'Mata Pelajaran',
    placeholder: 'Mata Pelajaran',
    md: 6,
    type: 'select',
    data: [],
  },
  {
    name: 'grade',
    label: 'Tingkatan',
    placeholder: 'Tingkatan',
    md: 6,
    type: 'select',
    data: [],
  },
  {
    name: 'teacher',
    label: 'Guru',
    placeholder: 'Ketik guru yang diinginkan',
    md: 6,
    type: 'search',
    data: [],
  },
];

export const formAddTeacher = [
  {
    name: 'teacher',
    label: 'Guru',
    placeholder: 'Ketik guru yang diinginkan',
    md: 6,
    type: 'select',
    data: [],
  },
  {
    name: 'grade',
    label: 'Tingkatan',
    placeholder: 'Tingkatan',
    md: 6,
    type: 'select',
    data: [],
  },
  {
    name: 'subject',
    label: 'Mata Pelajaran',
    placeholder: 'Mata Pelajaran',
    md: 6,
    type: 'search',
    data: [],
  },
];

export const formAddAnnouncement = [
  {
    name: 'title',
    label: 'Judul',
    placeholder: 'Ketik judul yang diinginkan',
    md: 6,
    type: 'text',
  },
  {
    name: 'text',
    label: 'Deskripsi',
    placeholder: 'Masukan deskripsi yang diinginkan',
    md: 6,
    type: 'textField',
  },
  {
    name: 'target',
    label: 'Target',
    placeholder: 'Pilih target yang diinginkan',
    md: 6,
    type: 'multiple-select',
    data: [
      { slug: 'student', title: 'Siswa' },
      { slug: 'staff', title: 'Staf' },
    ],
  },
  {
    name: 'image_uri',
    label: 'Gambar',
    placeholder: 'Gambar',
    md: 6,
    type: 'file',
  },
];

export const formAddStudentGroup = [
  {
    name: 'name',
    label: 'Kelas Wajib',
    placeholder: 'Kelas',
    md: 6,
    type: 'text',
  },
  {
    name: 'homeroom_teacher_id',
    label: 'Wali Kelas',
    placeholder: 'Wali Kelas',
    md: 6,
    type: 'select',
    data: [],
  },
  {
    name: 'period_id',
    label: 'Periode',
    placeholder: 'Periode',
    md: 6,
    type: 'select',
    data: [],
  },
  {
    name: 'study_program_id',
    label: 'Program Studi',
    placeholder: 'Program Studi',
    md: 6,
    type: 'select',
    data: [],
  },
  {
    name: 'grade',
    label: 'Tingkatan',
    placeholder: 'Tingkatan',
    md: 6,
    type: 'select',
    data: [],
  },
];

export const formAddExtracurriculer = [
  {
    name: 'title',
    label: 'Nama Ekstrakurikuler',
    placeholder: 'Ketik nama yang diinginkan',
    md: 6,
    type: 'text',
  },
  {
    name: 'teacher',
    label: 'Pembina',
    placeholder: 'Pilih Pembina yang diinginkan',
    md: 6,
    type: 'select',
    data: [],
  },
];

export const formAddStudentInExtracurriculer = [
  {
    name: 'title',
    label: 'Nama Extracurriculer',
    placeholder: 'Ketik nama yang diinginkan',
    md: 6,
    type: 'select',
    data: [],
  },
  {
    name: 'student',
    label: 'Murid',
    placeholder: 'Pilih Pembina yang diinginkan',
    md: 6,
    type: 'select',
    data: [],
  },
];

export const formAddStudent = [
  {
    name: 'student',
    label: 'Nama Siswa',
    placeholder: 'Pilih Nama yang diinginkan',
    md: 6,
    type: 'select',
    data: [],
  },
  {
    name: 'study_program',
    label: 'Program Study',
    placeholder: 'Pilih Program yang diinginkan',
    md: 6,
    type: 'select',
    data: [],
  },
  {
    name: 'grade',
    label: 'Tingkatan',
    placeholder: 'Pilih Tingkatan yang diinginkan',
    md: 6,
    type: 'select',
    data: [],
  },
];

export const formInsertStudentGroup = [
  {
    name: 'class',
    label: 'Kelas Wajib',
    placeholder: 'Pilih Tingkatan yang diinginkan',
    md: 6,
    type: 'select',
    data: [],
  },
  {
    name: 'student',
    label: 'Nama Siswa',
    placeholder: 'Pilih Nama yang diinginkan',
    md: 6,
    type: 'select',
    data: [],
  },
];
