import {
  educationLevels,
  genders,
  guardians,
  incomeLevels,
  lifeStatus,
  nationalities,
  nationality,
  permissions,
  relationships,
  religions,
  subject_types,
  types,
} from "@/globalcomponents/Variable";

export const formAddCurriculumFields = [
  {
    name: "period_name",
    label: "Periode",
    placeholder: "Periode",
    md: 6,
    type: "select",
    data: [
      { slug: "Tahun Ajaran 2024/2025", title: "Tahun Ajaran 2024/2025" },
      { slug: "Tahun Ajaran 2023/2024", title: "Tahun Ajaran 2023/2024" },
      { slug: "Tahun Ajaran 2022/2023", title: "Tahun Ajaran 2022/2023" },
    ],
  },
  {
    name: "study_program",
    label: "Program Studi",
    placeholder: "Program Studi",
    md: 6,
    type: "select",
    data: [
      { slug: "IPA", title: "IPA" },
      { slug: "IPS", title: "IPS" },
      { slug: "IPA-U", title: "IPA-U" },
      { slug: "IPS-U", title: "IPS-U" },
    ],
  },
  {
    name: "grade",
    label: "Tingkatan",
    placeholder: "Tingkatan",
    md: 6,
    type: "select",
    data: [
      { slug: "X", title: "X" },
      { slug: "XI", title: "XI" },
      { slug: "XII", title: "XII" },
      
    ],
  },
  {
    name: "curriculum",
    label: "Kurikulum",
    placeholder: "Kurikulum",
    md: 6,
    type: "select",
    data: [
      { slug: "Kurikulum Merdeka", title: "Kurikulum Merdeka" },
      { slug: "Kurikulum 2013", title: "Kurikulum 2013" },
      { slug: "Kurikulum Sekolah Sisva", title: "Kurikulum Sekolah Sisva" },
    ],
  },
];
export const formEditPeriodFields = [
  {
    name: "period_name",
    label: "Periode",
    placeholder: "Periode",
    md: 6,
    type: "text",
  },
  {
    name: "period",
    label: "Rentang Waktu",
    placeholder: "Rentang Waktu",
    md: 6,
    type: "month-range",
  },
  {
    name: "status",
    label: "Status",
    placeholder: "Status",
    md: 6,
    type: "select",
    data: [
      { slug: "Tidak Aktif", title: "Tidak Aktif" },
      { slug: "Aktif", title: "Aktif" },
    ],
  },
];
export const formAddPeriodFields = [
  {
    name: "period_name",
    label: "Periode",
    placeholder: "Periode",
    md: 6,
    type: "text",
  },
 
  {
    name: "period",
    label: "Rentang Waktu",
    placeholder: "Rentang Waktu",
    md: 6,
    type: "month-range",
  },
];
export const formAddSyllabusFields = [
  {
    name: "name",
    label: "Nama",
    placeholder: "Nama",
    md: 6,
    type: "select",
    data: [
      { slug: "Kurikulum Merdeka", title: "Kurikulum Merdeka" },
      { slug: "Kurikulum 2013", title: "Kurikulum 2013" },
      { slug: "Kurikulum Sekolah Sisva", title: "Kurikulum Sekolah Sisva" },
    ],
  },
  {
    name: "study_program",
    label: "Program Studi",
    placeholder: "Program Studi",
    md: 6,
    type: "select",
    data: [
      { slug: "IPA", title: "IPA" },
      { slug: "IPS", title: "IPS" },
      { slug: "IPA-U", title: "IPA-U" },
      { slug: "IPS-U", title: "IPS-U" },
    ],
  },
  {
    name: "subject",
    label: "Mata Pelajaran",
    placeholder: "Mata Pelajaran",
    md: 6,
    type: "select",
    data: [
      { slug: "Matematika", title: "Matematika" },
      { slug: "Fisika", title: "Fisika" },
      { slug: "Kimia", title: "Kimia" },
      { slug: "Biologi", title: "Biologi" },
      { slug: "Bahasa Inggris", title: "Bahasa Inggris" },
      { slug: "Bahasa Indonesia", title: "Bahasa Indonesia" },
      {
        slug: "Pendidikan Agama dan Budi Pekerti",
        title: "Pendidikan Agama dan Budi Pekerti",
      },
      {
        slug: "Pendidikan Pancasila dan Kewarganegaraan (PPKn)",
        title: "Pendidikan Pancasila dan Kewarganegaraan (PPKn)",
      },
      { slug: "Seni dan Budaya", title: "Seni dan Budaya" },
      {
        slug: "Pendidikan Jasmani, Olahraga, dan Kesehatan (PJOK)",
        title: "Pendidikan Jasmani, Olahraga, dan Kesehatan (PJOK)",
      },
      { slug: "Kewirausahaan", title: "Kewirausahaan" },
      {
        slug: "Teknologi Informasi dan Komunikasi (TIK)",
        title: "Teknologi Informasi dan Komunikasi (TIK)",
      },
    ],
  },
  {
    name: "grade",
    label: "Tingkatan",
    placeholder: "Tingkatan",
    md: 6,
    type: "select",
    data: [
      { slug: "X", title: "X" },
      { slug: "XI", title: "XI" },
      { slug: "XII", title: "XII" },
    ],
  },
  {
    name: "syllabus_uri",
    label: "Silabus",
    placeholder: "Silabus",
    md: 6,
    type: "file",
  },
];
export const formAddSubjectFields = [
  {
    name: "name",
    label: "Nama",
    placeholder: "Nama",
    md: 6,
    type: "select",
    data: [
      { slug: "Kurikulum Merdeka", title: "Kurikulum Merdeka" },
      { slug: "Kurikulum 2013", title: "Kurikulum 2013" },
      { slug: "Kurikulum Sekolah Sisva", title: "Kurikulum Sekolah Sisva" },
    ],
  },
  {
    name: "study_program",
    label: "Program Studi",
    placeholder: "Program Studi",
    md: 6,
    type: "select",
    data: [
      { slug: "IPA", title: "IPA" },
      { slug: "IPS", title: "IPS" },
      { slug: "IPA-U", title: "IPA-U" },
      { slug: "IPS-U", title: "IPS-U" },
    ],
  },
  {
    name: "subject",
    label: "Mata Pelajaran",
    placeholder: "Mata Pelajaran",
    md: 6,
    type: "text",
  },
  {
    name: "subject_type",
    label: "Tipe",
    placeholder: "Tipe",
    md: 6,
    type: "select",
    data: subject_types,
  },
];
export const formAddStudyProgramFields = [
  {
    name: "name",
    label: "Program Studi",
    placeholder: "Nama",
    md: 6,
    type: "text",
  },
  {
    name: "code",
    label: "Kode",
    placeholder: "Kode",
    md: 6,
    type: "text",
  },
];

export const formAddStaffFields = [
  {
    name: "name",
    label: "Nama",
    placeholder: "Nama",
    md: 6,
    type: "text",
  },
  {
    name: "username",
    label: "Username",
    placeholder: "Username",
    md: 6,
    type: "text",
  },
  {
    name: "type",
    label: "Tipe",
    placeholder: "Tipe",
    md: 6,
    type: "select",
    data: types,
  },
  {
    name: "permissions",
    label: "Akses",
    placeholder: "Akses",
    md: 6,
    type: "multiple-select",
    data: permissions,
  },
  {
    name: "password",
    label: "Password",
    placeholder: "Password",
    md: 6,
    type: "password",
  },
  {
    name: "password_confirm",
    label: "Konfirmasi Password",
    placeholder: "Konfirmasi Password",
    md: 6,
    type: "password",
  },
];
export const formAddStudentFields = [
  {
    name: "name",
    label: "Nama",
    placeholder: "Nama",
    md: 6,
    type: "text",
  },
  {
    name: "username",
    label: "Username",
    placeholder: "Username",
    md: 6,
    type: "text",
  },
  {
    name: "password",
    label: "Password",
    placeholder: "Password",
    md: 6,
    type: "password",
  },
  {
    name: "password_confirm",
    label: "Konfirmasi Password",
    placeholder: "Konfirmasi Password",
    md: 6,
    type: "password",
  },
];

export const formStudentBasicFields = [
  {
    name: "name",
    label: "Nama",
    placeholder: "Nama",
    md: 6,
    type: "text",
  },
  {
    name: "username",
    label: "Username",
    placeholder: "Username",
    md: 6,
    type: "text",
  },
];

export const formStudentBiodataFields = [
  {
    name: "email",
    label: "Email",
    placeholder: "Email",
    md: 6,
    type: "text",
  },
  {
    name: "phone",
    label: "Nomor Telepon",
    placeholder: "Nomor Telepon",
    md: 6,
    type: "text",
  },
  {
    name: "gender",
    label: "Jenis Kelamin",
    placeholder: "Jenis Kelamin",
    md: 6,
    type: "select",
    data: genders,
  },
  {
    name: "nationality",
    label: "Kewarganegaraan",
    placeholder: "Kewarganegaraan",
    md: 6,
    type: "select",
    data: nationalities,
  },
  {
    name: "personal_id",
    label: "NIK",
    placeholder: "NIK",
    md: 6,
    type: "text",
  },
  {
    name: "education_id",
    label: "NISN",
    placeholder: "NISN",
    md: 6,
    type: "text",
  },
  {
    name: "religion",
    label: "Agama",
    placeholder: "Agama",
    md: 12,
    type: "select",
    data: religions,
  },
  {
    name: "address",
    label: "Alamat",
    placeholder: "Alamat",
    md: 12,
    type: "text",
  },
  {
    name: "profile_image_uri",
    label: "Foto Profil",
    placeholder: "Foto Profil",
    md: 12,
    type: "photo",
  },
];

export const formStudentParentsFields = [
  { type: "title", label: "Wali Murid" },
  {
    name: "guardian_type",
    // label: "Wali Murid",
    // placeholder: "Wali Murid",
    md: 12,
    type: "select",
    data: guardians,
  },
  { type: "divider" },
  { type: "title", label: "Informasi Ayah" },
  {
    name: "father_name",
    label: "Nama",
    placeholder: "Nama",
    md: 12,
    type: "text",
  },
  {
    name: "father_email",
    label: "Email",
    placeholder: "Email",
    md: 6,
    type: "text",
  },
  {
    name: "father_phone",
    label: "Nomor Telepon",
    placeholder: "Nomor Telepon",
    md: 6,
    type: "text",
  },
  {
    name: "father_occupation",
    label: "Profesi",
    placeholder: "Profesi",
    md: 6,
    type: "text",
  },
  {
    name: "father_education",
    label: "Pendidikan Terakhir",
    placeholder: "Pendidikan Terakhir",
    md: 6,
    type: "select",
    data: educationLevels,
  },
  {
    name: "father_income",
    label: "Pemasukan Bulanan",
    placeholder: "Pemasukan Bulanan",
    md: 12,
    type: "select",
    data: incomeLevels,
  },
  {
    name: "father_birth_year",
    label: "Tahun Lahir",
    placeholder: "Tahun Lahir",
    md: 6,
    type: "text",
  },
  {
    name: "father_life_status",
    label: "Status",
    placeholder: "Status",
    md: 6,
    type: "select",
    data: lifeStatus,
  },
  {
    name: "father_religion",
    label: "Agama",
    placeholder: "Agama",
    md: 12,
    type: "select",
    data: religions,
  },
  {
    name: "father_address",
    label: "Alamat",
    placeholder: "Alamat",
    md: 12,
    type: "text",
  },
  { type: "divider" },
  { type: "title", label: "Informasi Ibu" },
  {
    name: "mother_name",
    label: "Nama",
    placeholder: "Nama",
    md: 12,
    type: "text",
  },
  {
    name: "mother_occupation",
    label: "Profesi",
    placeholder: "Profesi",
    md: 6,
    type: "text",
  },
  {
    name: "mother_education",
    label: "Pendidikan Terakhir",
    placeholder: "Pendidikan Terakhir",
    md: 6,
    type: "select",
    data: educationLevels,
  },
  {
    name: "mother_income",
    label: "Pemasukan Bulanan",
    placeholder: "Pemasukan Bulanan",
    md: 12,
    type: "select",
    data: incomeLevels,
  },
  {
    name: "mother_email",
    label: "Email",
    placeholder: "Email",
    md: 6,
    type: "text",
  },
  {
    name: "mother_phone",
    label: "Nomor Telepon",
    placeholder: "Nomor Telepon",
    md: 6,
    type: "text",
  },
  {
    name: "mother_birth_year",
    label: "Tahun Lahir",
    placeholder: "Tahun Lahir",
    md: 6,
    type: "text",
  },
  {
    name: "mother_life_status",
    label: "Status",
    placeholder: "Status",
    md: 6,
    type: "select",
    data: lifeStatus,
  },
  {
    name: "mother_religion",
    label: "Agama",
    placeholder: "Agama",
    md: 12,
    type: "select",
    data: religions,
  },
  {
    name: "mother_address",
    label: "Alamat",
    placeholder: "Alamat",
    md: 12,
    type: "text",
  },

  { type: "divider" },
  { type: "title", label: "Informasi Wali" },
  {
    name: "guardian_name",
    label: "Nama",
    placeholder: "Nama",
    md: 12,
    type: "text",
  },
  {
    name: "guardian_gender",
    label: "Jenis Kelamin",
    placeholder: "Jenis Kelamin",
    md: 6,
    type: "select",
    data: genders,
  },
  {
    name: "guardian_relationship",
    label: "Hubungan",
    placeholder: "Hubungan",
    md: 6,
    type: "select",
    data: relationships,
  },
  {
    name: "guardian_occupation",
    label: "Profesi",
    placeholder: "Profesi",
    md: 6,
    type: "text",
  },
  {
    name: "guardian_education",
    label: "Pendidikan Terakhir",
    placeholder: "Pendidikan Terakhir",
    md: 6,
    type: "select",
    data: educationLevels,
  },
  {
    name: "guardian_income",
    label: "Pemasukan Bulanan",
    placeholder: "Pemasukan Bulanan",
    md: 12,
    type: "select",
    data: incomeLevels,
  },
  {
    name: "guardian_email",
    label: "Email",
    placeholder: "Email",
    md: 6,
    type: "text",
  },
  {
    name: "guardian_phone",
    label: "Nomor Telepon",
    placeholder: "Nomor Telepon",
    md: 6,
    type: "text",
  },
  {
    name: "guardian_birth_year",
    label: "Tahun Lahir",
    placeholder: "Tahun Lahir",
    md: 6,
    type: "text",
  },
  {
    name: "guardian_life_status",
    label: "Status",
    placeholder: "Status",
    md: 6,
    type: "select",
    data: lifeStatus,
  },
  {
    name: "guardian_religion",
    label: "Agama",
    placeholder: "Agama",
    md: 12,
    type: "select",
    data: religions,
  },
  {
    name: "guardian_address",
    label: "Alamat",
    placeholder: "Alamat",
    md: 12,
    type: "text",
  },
];

export const formStaffBasicFields = [
  {
    name: "name",
    label: "Nama",
    placeholder: "Nama",
    md: 6,
    type: "text",
  },
  {
    name: "username",
    label: "Username",
    placeholder: "Username",
    md: 6,
    type: "text",
  },
  {
    name: "type",
    label: "Tipe",
    placeholder: "Tipe",
    md: 6,
    type: "select",
    data: types,
  },
  {
    name: "permissions",
    label: "Akses",
    placeholder: "Akses",
    md: 6,
    type: "multiple-select",
    data: permissions,
  },
];

export const formStaffBiodataFields = [
  {
    name: "email",
    label: "Email",
    placeholder: "Email",
    md: 6,
    type: "text",
  },
  {
    name: "phone",
    label: "Nomor Telepon",
    placeholder: "Nomor Telepon",
    md: 6,
    type: "text",
  },
  {
    name: "gender",
    label: "Jenis Kelamin",
    placeholder: "Jenis Kelamin",
    md: 6,
    type: "select",
    data: genders,
  },
  {
    name: "nationality",
    label: "Kewarganegaraan",
    placeholder: "Kewarganegaraan",
    md: 6,
    type: "select",
    data: nationalities,
  },
  {
    name: "personal_id",
    label: "NIK",
    placeholder: "NIK",
    md: 6,
    type: "text",
  },
  {
    name: "education_id",
    label: "NUPTK",
    placeholder: "NUPTK",
    md: 6,
    type: "text",
  },
  {
    name: "religion",
    label: "Agama",
    placeholder: "Agama",
    md: 12,
    type: "select",
    data: religions,
  },
  {
    name: "address",
    label: "Alamat",
    placeholder: "Alamat",
    md: 12,
    type: "text",
  },
  {
    name: "profile_image_uri",
    label: "Foto Profil",
    placeholder: "Foto Profil",
    md: 12,
    type: "photo",
  },
];

export const formChangePasswordFields = [
  {
    name: "old_password",
    label: "Password Lama",
    placeholder: "Password Lama",
    md: 12,
    type: "password",
  },
  {
    name: "new_password",
    label: "Password Baru",
    placeholder: "Password Baru",
    md: 6,
    type: "password",
  },
  {
    name: "new_password_confirm",
    label: "Konfirmasi Password Baru",
    placeholder: "Konfirmasi Password Baru",
    md: 6,
    type: "password",
  },
];
export const formResetPasswordFields = [
  {
    name: "new_password",
    label: "Password Baru",
    placeholder: "Password Baru",
    md: 6,
    type: "password",
  },
  {
    name: "new_password_confirm",
    label: "Konfirmasi Password Baru",
    placeholder: "Konfirmasi Password Baru",
    md: 6,
    type: "password",
  },
];

export const formSchoolDetailsFields = [
  {
    name: "name",
    label: "Nama Sekolah",
    placeholder: "Nama Sekolah",
    md: 6,
    image: false,
  },
  {
    name: "abbreviation",
    label: "Nama Singkatan",
    placeholder: "Nama Singkatan",
    md: 6,
    image: false,
  },
  {
    name: "identifier_value",
    label: "NPSN",
    placeholder: "NPSN",
    md: 6,
    image: false,
  },
  {
    name: "code",
    label: "Kode Sekolah",
    placeholder: "Kode Sekolah",
    md: 6,
    image: false,
  },
  {
    name: "email",
    label: "Email",
    placeholder: "Email",
    md: 6,
    image: false,
  },
  {
    name: "phone",
    label: "Nomor Telepon",
    placeholder: "Nomor Telepon",
    md: 6,
    image: false,
  },
  {
    name: "address",
    label: "Alamat",
    placeholder: "Alamat Sekolah",
    md: 12,
    image: false,
  },
  {
    name: "logo_uri",
    label: "Logo Sekolah",
    placeholder: "Upload logo untuk identitas sekolah",
    md: 12,
    image: true,
  },
];

export const formSchoolTypeFields = [
  {
    name: "education_type",
    label: "Jenis Sekolah",
    placeholder: "Jenis Sekolah",
    md: 6,
    image: false,
    data: [
      {
        value: "public",
        label: "Umum",
      },
      {
        value: "madrasa",
        label: "Madrasah",
      },
      {
        value: "other",
        label: "Lainnya",
      },
    ],
  },
  {
    name: "education_level",
    label: "Tingkatan Sekolah",
    placeholder: "Tingkatan Sekolah",
    md: 6,
    image: false,
    data: [
      {
        value: "kindergarten",
        label: "TK/RA",
      },
      {
        value: "elementary_school",
        label: "SD/MI",
      },
      {
        value: "middle_school",
        label: "SMP/MTS",
      },
      {
        value: "highschool",
        label: "SMA/SMK/MA",
      },
      {
        value: "others",
        label: "Lainnya",
      },
    ],
  },
  {
    name: "ownership_type",
    label: "Kepemilikan Sekolah",
    placeholder: "Kepemilikan Sekolah",
    md: 6,
    image: false,
    data: [
      {
        value: "state",
        label: "Negeri",
      },
      {
        value: "private",
        label: "Swasta",
      },
    ],
  },
];
